<?php
/**
 * Theme functions and definitions.
 * This child theme was generated by Real Estate 7.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 */

/*
 * If your child theme has more than one .css file (eg. ie.css, style.css, main.css) then
 * you will have to make sure to maintain all of the parent theme dependencies.
 *
 * Make sure you're using the correct handle for loading the parent theme's styles.
 * Failure to use the proper tag will result in a CSS file needlessly being loaded twice.
 * This will usually not affect the site appearance, but it's inefficient and extends your page's loading time.
 *
 * @link https://codex.wordpress.org/Child_Themes
 */
 
 /*function listing_slider_shortcode() {
  $string = '';
  $string .= 'Message';
  return $string;
 } //if container. If image one isn't loaed, the slider won't show.
  add_shortcode('listing-slider', 'listing_slider_shortcode');*/
 
 include 'listing-slider/modern-listing-slider.php';
 
 function realestate_child_enqueue_styles() {
  
     wp_enqueue_style( 'realestate-7-style' , get_template_directory_uri() . '/style.css' );
     wp_enqueue_style( 'realestate-7-child-style', get_stylesheet_directory_uri() . '/style.css', array( 'realestate-7-style' ), wp_get_theme()->get('Version')
     );
     
     wp_enqueue_style( 'font-awesome', get_stylesheet_directory_uri() . '/listing-slider/font-awesome-4.6.3/css/font-awesome.min.css', array(), '2018', 'all' );
 

     if ( 'listings' == get_post_type() ) {
      
      wp_register_style('bootstrap-listings', get_stylesheet_directory_uri() . '/listing-slider/css/bootstrap.min.css', array(), '', 'all');
      wp_enqueue_style('bootstrap-listings');
 
      //wp_register_style( 'thumbnail-image', get_stylesheet_directory_uri() . '/listing-slider/css/thumbnail_image_carousel.css', array(), '2018', 'all' );
      //wp_enqueue_style( 'thumbnail-image' );
 
     // wp_register_style( 'gpproduct', get_stylesheet_directory_uri() . '/listing-slider/css/gp_product_carousel_advance.css', array(), '2018', 'all' );
      //wp_enqueue_style( 'gpproduct' );
      
    
      wp_register_script('oldjquery', 'https://code.jquery.com/jquery-1.12.4.min.js', array(), '1.12.4', false);
      wp_enqueue_script('oldjquery');
 
      //wp_enqueue_script('custom-js', get_stylesheet_directory_uri() . '/js/custom.js', array(), '', true);
 
      wp_register_script('bootstrap-js', get_stylesheet_directory_uri() . '/listing-slider/js/bootstrap.min.js', array(), '1.12.4', true);
      wp_enqueue_script('bootstrap-js');
    
      //wp_register_script('touchSwipe', get_stylesheet_directory_uri() . '/listing-slider/js/jquery.touchSwipe.min.js', array(), '1.6.9', true);
      //wp_enqueue_script('touchSwipe');
    
      //wp_register_script('bootstrap-carousel', get_stylesheet_directory_uri() . '/listing-slider/js/responsive_bootstrap_carousel.js', array(), '1.6.9', true);
      //wp_enqueue_script('bootstrap-carousel');
     }
     
     if ( 'listings' != get_post_type() ) {
 
      wp_register_style('bootstrap-css-v5', '//cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css', array(), '', 'all');
      wp_enqueue_style('bootstrap-css-v5');
      
      wp_register_script('bootstrap-js-v5', '//cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js', array(), '5.1.3', true);
      wp_enqueue_script('bootstrap-js-v5');
      
     }

 }
 
 add_action(  'wp_enqueue_scripts', 'realestate_child_enqueue_styles' );
 
 add_action('wp_footer','load_modal_front_page', 5);
 function load_modal_front_page() {
  
  echo '
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
     <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
       <div class="modal-body">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        <div class="10 columns request-quote-display-desktop">
         <div id="advanced-search-inner" class="quote-form front-page-modal">
         <h3>Request A Quote</h3>'
       . do_shortcode('[gravityform id="21" name="Request A Quote" ajax="true" title="false" description="false"]') .
        '</div>
        </div>
       </div>
       <div class="modal-footer">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
       </div>
      </div>
     </div>
    </div>
   ';
 }

